In [70]:
for i in range(0, 11):
    print(i)

0
1
2
3
4
5
6
7
8
9
10

In [71]:
i=-1
while i<10:
    i=i+1
    print (i)

0
1
2
3
4
5
6
7
8
9
10

In [72]:
for i in range(10,-1,-1):
    print(i,end=" ")

10 9 8 7 6 5 4 3 2 1 0

In [2]:
i=11
while i>0:
    i=i-1
    print (i)

10
9
8
7
6
5
4
3
2
1
0

In [38]:
for i in range (0,8):   
    for j in range (0,8):  
        print ("#", end=" "),
    print (" ")

# # # # # # # #
# # # # # # # #
# # # # # # # #
# # # # # # # #
# # # # # # # #
# # # # # # # #
# # # # # # # #
# # # # # # # #

In [6]:
layer = 7

for x in range(1,8):

    space_num = layer - x
    for y in range(1, space_num + 1):
        print(" ", end="")

    star_num = 2 * x - 1
    for y in range(1, star_num + 1):
        print("#", end="")
    print("")

      #
     ###
    #####
   #######
  #########
 ###########
#############

In [48]:
first = [0,1,2,3,4,5,6,7,8,9,10]
second = [0,1,2,3,4,5,6,7,8,9,10]
for i in first:
    for j in second:
        if i != j:
            continue
        print(i, '*', j, '= ', i * j)

0 * 0 =  0
1 * 1 =  1
2 * 2 =  4
3 * 3 =  9
4 * 4 =  16
5 * 5 =  25
6 * 6 =  36
7 * 7 =  49
8 * 8 =  64
9 * 9 =  81
10 * 10 =  100

In [51]:
list=['Python', 'Numpy','Pandas','Scikit', 'Pytorch']
for i in list:
    print(i)

Python
Numpy
Pandas
Scikit
Pytorch

In [61]:
for i in range(0,101):
    if i % 2==0:
        print(i)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100

In [60]:
for i in range(0,101):
    if i % 2!=0:
        print(i)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99

In [59]:
sum=0
for i in range(0,101):
    sum+=i
    print(sum)

0
1
3
6
10
15
21
28
36
45
55
66
78
91
105
120
136
153
171
190
210
231
253
276
300
325
351
378
406
435
465
496
528
561
595
630
666
703
741
780
820
861
903
946
990
1035
1081
1128
1176
1225
1275
1326
1378
1431
1485
1540
1596
1653
1711
1770
1830
1891
1953
2016
2080
2145
2211
2278
2346
2415
2485
2556
2628
2701
2775
2850
2926
3003
3081
3160
3240
3321
3403
3486
3570
3655
3741
3828
3916
4005
4095
4186
4278
4371
4465
4560
4656
4753
4851
4950
5050

In [65]:
sum=0
for i in range(0,101):
    if i % 2==0:
        sum+=i
    print(sum)

0
0
2
2
6
6
12
12
20
20
30
30
42
42
56
56
72
72
90
90
110
110
132
132
156
156
182
182
210
210
240
240
272
272
306
306
342
342
380
380
420
420
462
462
506
506
552
552
600
600
650
650
702
702
756
756
812
812
870
870
930
930
992
992
1056
1056
1122
1122
1190
1190
1260
1260
1332
1332
1406
1406
1482
1482
1560
1560
1640
1640
1722
1722
1806
1806
1892
1892
1980
1980
2070
2070
2162
2162
2256
2256
2352
2352
2450
2450
2550

In [66]:
sum=0
for i in range(0,101):
    if i % 2!=0:
        sum+=i
    print(sum)

0
1
1
4
4
9
9
16
16
25
25
36
36
49
49
64
64
81
81
100
100
121
121
144
144
169
169
196
196
225
225
256
256
289
289
324
324
361
361
400
400
441
441
484
484
529
529
576
576
625
625
676
676
729
729
784
784
841
841
900
900
961
961
1024
1024
1089
1089
1156
1156
1225
1225
1296
1296
1369
1369
1444
1444
1521
1521
1600
1600
1681
1681
1764
1764
1849
1849
1936
1936
2025
2025
2116
2116
2209
2209
2304
2304
2401
2401
2500
2500

In [1]:
countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombi',
  'Comoros',
  'Congo (Brazzaville)',
  'Congo',
  'Costa Rica',
  "Cote d'Ivoire",
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor (Timor Timur)',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia, The',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea, North',
  'Korea, South',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia and Montenegro',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];
target = "land"
for word in countries:
    if target in word:
        print(word)

Finland
Iceland
Ireland
Marshall Islands
Netherlands
New Zealand
Poland
Solomon Islands
Swaziland
Switzerland
Thailand

In [2]:
list1 = ['banana', 'orange', 'mango', 'lemon'] 
for num in reversed(list1):
    print(num)

lemon
mango
orange
banana